---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-sparkoperator-k8s-io-v1beta2-sparkapplication
  failurePolicy: Fail
  name: msparkapplication.kb.io
  rules:
  - apiGroups:
    - sparkoperator.k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - sparkapplications
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sparkoperator-k8s-io-v1beta2-sparkapplication
  failurePolicy: Fail
  name: msparkapplication.kb.io
  rules:
  - apiGroups:
    - sparkoperator.k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduledsparkapplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sparkoperator-k8s-io-v1beta2-scheduledsparkapplication
  failurePolicy: Fail
  name: vsparkapplication.kb.io
  rules:
  - apiGroups:
    - sparkoperator.k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduledsparkapplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sparkoperator-k8s-io-v1beta2-sparkapplication
  failurePolicy: Fail
  name: vsparkapplication.kb.io
  rules:
  - apiGroups:
    - sparkoperator.k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - sparkapplications
  sideEffects: None
