{{- if .Values.webhook.enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-operator.webhookSecretName" . }}
  annotations:
    cert-manager.io/allow-direct-injection: "true"
data:
  ca.crt: ""
  tls.key: ""
  tls.crt: ""
{{- end }}
