{{- if .Values.webhook.enable -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "spark-operator.webhookServiceName" . }}
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "spark-operator.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.webhook.port }}
    targetPort: {{ .Values.webhook.portName }}
    name: {{ .Values.webhook.portName }}
{{- end }}
